# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
stages:
  - test
  - homolog
  - deploy
test:
  stage: test
  script:
    - echo "teste realizado com suscesso"
build to homolog:
  stage: homolog
  script:
    - echo "taking to homolog"
    - cp * /usr/share/nginx/hom/
  only:
    - branches
    - tags
  except:
    - master
  tags:
    - homolog
  environment: homolog
  when: always
deploy to production:
  stage: deploy
  script:
    - echo "deploying to production"
    - cp * /usr/share/nginx/www/
  only:
    - tags
    - master
  environment: production
  when: manual
  tags:
    - production
